discordBot:
  token: 'MTAyMDYxMjc3MzU4OTI5MTA0OA.GKe_rw.chn60bI2xKa_G_CsQG0xV3zL1t2z7w5UEToLtw' # Enter your bot token here
  text: 'Testing' # The text for the discord bot
  type: 'watching' # This can be set to 'watching', 'playing', 'listening', or 'competing'
  status: 'online' # This can be set to 'online', 'idle', 'dnd'(do not disturb), or 'invisible'

discordServer:
  channelID: '1020619434450243614' # Set this to the channel ID where you want notifications to be sent
  liveChannelID: '1020619434450243614' # Set this to the channel ID where you want the status message to be sent

statusText:
  online: ':online: Online'
  offline: ':offline: Offline'

statusMessage:
  online:
    title: '{name} is back online!' # Use {name} to specify the node name. Will just display 'Panel' if the message is for the panel
    description: 'Thanks for your patience!

    We will try to prevent this happening again :tools:' # Use {name} to specify the node name. Will just display 'Panel' if the message is for the panel
    footer: 'WebWorks Update' # Use {name} to specify the node name. Will just display 'Panel' if the message is for the panel
    colour: 5763719 # Must be as discords form, AKA Int value. If you don't know how to convert, you can use this website https://www.mathsisfun.com/hexadecimal-decimal-colors.html
    timestamp: true # Whether you do or don't show the time on the message
    image: '' # Leave blank to have no image
    thumbnail: '' # Leave blank to have no thumbnail
  offline:
    title: '{name} is down!' # Use {name} to specify the node name. Will just display 'Panel' if the message is for the panel
    description: 'We apologize for the inconvenience!
    
    We will try to get this back up momentarily :tools:' # Use {name} to specify the node name. Will just display 'Panel' if the message is for the panel
    footer: 'WebWorks Update' # Use {name} to specify the node name. Will just display 'Panel' if the message is for the panel
    colour: 16718109 # Must be as discords form, AKA Int value. If you don't know how to convert, you can use this website https://www.mathsisfun.com/hexadecimal-decimal-colors.html
    timestamp: true # Whether you do or don't show the time on the message
    image: '' # Leave blank to have no image
    thumbnail: '' # Leave blank to have no thumbnail

liveMessage:
  title: 'WebWorks Server Status'
  description: 'WebWorks Server Status'
  footer: 'WebWorks'
  colour: '5763719' # Must be as discords form, AKA Int value. If you don't know how to convert, you can use this website https://www.mathsisfun.com/hexadecimal-decimal-colors.html
  timestamp: true # Whether you do or don't show the time on the message
  image: ''  # Leave blank to have no image
  thumbnail: ''  # Leave blank to have no thumbnail

messageButtons:
  enableButtons: true

  # Leave the text and url field blank to ignore the button
  button1:
    text: 'Website'
    url: 'https://webworkshub.online'
  button2:
    text: 'Panel'
    url: 'https://panel.webworkshub.online'
  button3:
    text: ''
    url: ''
  button4:
    text: ''
    url: ''
  button5:
    text: ''
    url: ''

pterodactyl:
  apiKey: 'ptla_ojkHeSPsKFLjG0vK7TRZav9dotBAuL0T5LZAv9ZG3k9' # Set this to your panel API key. It can be created @ https://yourpanel.com/admin/api
  url: 'https://panel.webworkshub.online' # Should start with https:// or http://. Should not contain any url slug. And MUST NOT contain the / at the end
  refresh: 60 # In seconds how long between update