loggingName: 'WebWorks Server Status' # Just for console logging

discordBot:
  token: '' # Enter your bot token here
  text: 'Testing' # The text for the discord bot
  type: 'watching' # This can be set to 'watching', 'playing', 'listening', or 'competing'
  status: 'online' # This can be set to 'online', 'idle', 'dnd'(do not disturb), or 'invisible'

discordServer:
  channelID: '' # Set this to the channel ID where you want notifications to be sent
  liveChannelID: '' # Set this to the channel ID where you want the status message to be sent

statusText:
  online: '<:online:1160669028323442708> Online'
  offline: '<:offline:1160669026117230633> Offline'

statusMessage:
  online:
    title: '{name} is back online!' # Use {name} to specify the node name. Will just display 'Panel' if the message is for the panel
    description: "Thanks for your patience!\n\nWe will try to prevent this happening again :tools:" # Use {name} to specify the node name. Will just display 'Panel' if the message is for the panel
    footer: 'WebWorks Update' # Use {name} to specify the node name. Will just display 'Panel' if the message is for the panel
    colour: 5763719 # Must be as discords form, AKA Int value. If you don't know how to convert, you can use this website https://www.mathsisfun.com/hexadecimal-decimal-colors.html
    timestamp: true # Whether you do or don't show the time on the message
    image: '' # Leave blank to have no image
    thumbnail: '' # Leave blank to have no thumbnail
  offline:
    title: '{name} is down!' # Use {name} to specify the node name. Will just display 'Panel' if the message is for the panel
    description: "We apologize for the inconvenience!\n\nWe will try to get this back up momentarily :tools:" # Use {name} to specify the node name. Will just display 'Panel' if the message is for the panel
    footer: 'WebWorks Update' # Use {name} to specify the node name. Will just display 'Panel' if the message is for the panel
    colour: 16718109 # Must be as discords form, AKA Int value. If you don't know how to convert, you can use this website https://www.mathsisfun.com/hexadecimal-decimal-colors.html
    timestamp: true # Whether you do or don't show the time on the message
    image: '' # Leave blank to have no image
    thumbnail: '' # Leave blank to have no thumbnail

liveMessage:
  title: 'WebWorks Server Status'
  description: 'WebWorks Server Status'
  footer: 'WebWorks'
  colour: 000000 # Must be as discords form, AKA Int value. If you don't know how to convert, you can use this website https://www.mathsisfun.com/hexadecimal-decimal-colors.html
  timestamp: true # Whether you do or don't show the time on the message
  image: ''  # Leave blank to have no image
  thumbnail: ''  # Leave blank to have no thumbnail

messageButtons:
  enableButtons: true

  # Leave the text and url field blank to ignore the button
  button1:
    text: 'Website'
    url: 'https://webworkshub.online'
  button2:
    text: 'Panel'
    url: 'https://panel.webworkshub.online'
  button3:
    text: ''
    url: ''
  button4:
    text: ''
    url: ''
  button5:
    text: ''
    url: ''

pterodactyl:
  apiKey: '' # Set this to your panel API key. It can be created @ https://yourpanel.com/admin/api
  url: '' # Should start with https:// or http://. Should not contain any url slug. And MUST NOT contain the / at the end
  refresh: 10 # In seconds how long between update.